displayName=Improved Exchange Logger
author=istid, Mreedon, clamzhi-dev
support=https://github.com/clamzhi-dev/improved-exchange-logger
description=Stores all GE transactions in a log file
tags=GE,grandexchange,log,exchange,logger
plugins=com.improvedexchangelogger.ImprovedExchangeLoggerPlugin
build=standard